package com.example.formulamaster.ui.theme

import androidx.compose.ui.graphics.Color

val BluePrimaryLight = Color(0xFF0061A4)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFD1E4FF)
val BlueOnPrimaryContainerLight = Color(0xFF001D36)
val BlueSecondaryLight = Color(0xFF535F70)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFD7E3F7)
val BlueOnSecondaryContainerLight = Color(0xFF101C2B)
val BlueTertiaryLight = Color(0xFF6B5778)
val BlueOnTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFFF2DAFF)
val BlueOnTertiaryContainerLight = Color(0xFF251431)
val BlueErrorLight = Color(0xFFBA1A1A)
val BlueOnErrorLight = Color(0xFFFFFFFF)
val BlueErrorContainerLight = Color(0xFFFFDAD6)
val BlueOnErrorContainerLight = Color(0xFF410002)
val BlueBackgroundLight = Color(0xFFFDFCFF)
val BlueOnBackgroundLight = Color(0xFF1A1C1E)
val BlueSurfaceLight = Color(0xFFFDFCFF)
val BlueOnSurfaceLight = Color(0xFF1A1C1E)
val BlueSurfaceVariantLight = Color(0xFFDFE2EB)
val BlueOnSurfaceVariantLight = Color(0xFF43474E)
val BlueOutlineLight = Color(0xFF73777F)

val BluePrimaryDark = Color(0xFF9ECAFF)
val BlueOnPrimaryDark = Color(0xFF003258)
val BluePrimaryContainerDark = Color(0xFF00497D)
val BlueOnPrimaryContainerDark = Color(0xFFD1E4FF)
val BlueSecondaryDark = Color(0xFFBBC7DB)
val BlueOnSecondaryDark = Color(0xFF253140)
val BlueSecondaryContainerDark = Color(0xFF3B4858)
val BlueOnSecondaryContainerDark = Color(0xFFD7E3F7)
val BlueTertiaryDark = Color(0xFFD6BEE4)
val BlueOnTertiaryDark = Color(0xFF3B2948)
val BlueTertiaryContainerDark = Color(0xFF523F5F)
val BlueOnTertiaryContainerDark = Color(0xFFF2DAFF)
val BlueErrorDark = Color(0xFFFFB4AB)
val BlueOnErrorDark = Color(0xFF690005)
val BlueErrorContainerDark = Color(0xFF93000A)
val BlueOnErrorContainerDark = Color(0xFFFFDAD6)
val BlueBackgroundDark = Color(0xFF1A1C1E)
val BlueOnBackgroundDark = Color(0xFFE3E2E6)
val BlueSurfaceDark = Color(0xFF1A1C1E)
val BlueOnSurfaceDark = Color(0xFFE3E2E6)
val BlueSurfaceVariantDark = Color(0xFF43474E)
val BlueOnSurfaceVariantDark = Color(0xFFC3C7CF)
val BlueOutlineDark = Color(0xFF8D9199)
